---
- name: Cài đặt yum-utils và bật kho EPEL
  yum:
    name: '{{packages}}'
    state: present
  vars:
    packages:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Cấu hình kho lưu trữ PHP 7.2.
  shell: yum-config-manager --enable remi-php72

- name: Cài đặt PHP 7.2 cùng với các phụ thuộc.
  yum: 
    name:
      - php
      - php-common
      - php-opcache
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysql
    state: present