---
- name: Enable service httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
    
- name: Start service httpd
  ansible.builtin.service:
    name: httpd
    state: started

- name: Restart service httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Reload firewall-cmd
  shell: firewall-cmd --reload