---
- name: Start service mariadb
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Enable service mariadb
  ansible.builtin.service:
    name: mariadb
    enabled: yes

- name: Restart service mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Restart friewall services
  shell: firewall-cmd --reload